# Development environment overrides
# Extends docker-compose.yml with dev-specific settings

services:
  patient-frontend:
    networks:
      - plebemr_admin_network
      
  mgit-web:
    command: sh -c "npm install nodemon --save-dev 2>/dev/null; npx nodemon server.js"
    volumes:
      - ../private_repos:/private_repos
      - .:/app                    # Mount source code for hot reload
      - /app/node_modules          # Anonymous volume for node_modules
      - ./.env.development:/app/.env
    networks:
      - plebemr_admin_network

  gateway:
    ports:
      - "3003:80"
    networks:
      - plebemr_admin_network

  mysql:
    ports:
      - "3306:3306"              # Expose MySQL for local development
    networks:
      - plebemr_admin_network

  phpmyadmin:
    ports:
      - "8089:80"
    networks:
      - plebemr_admin_network

  plebdoc-api:
    ports:
      - "3005:3005"
    networks:
      - plebemr_admin_network

  swagger-ui:
    ports:
      - "8090:8080"
    networks:
      - plebemr_admin_network

networks:
  plebemr_admin_network:
    external: false