version: "3.7"

services:
  app_proxy:
    environment:
      BASE_URL: "https://plebemr.com"
      APP_HOST: mgitreposerver-mgit-repo-server_web_1
      APP_PORT: 3003
      
  web:
    image: imyjimmy/mgit-repo-server:latest
    restart: on-failure
    stop_grace_period: 1m
    environment:
      REPOS_PATH: /private_repos
      NODE_ENV: production
      # PORT: 3003
    volumes:
      # Repository storage (contains both git repos and SQLite database)
      - ${APP_DATA_DIR}/repos:/private_repos
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  appointments_proxy:
    environment:
      BASE_URL: "https://appointments.plebemr.com"
      APP_HOST: mgitreposerver-mgit-repo-server_appointments_nginx_1
      APP_PORT: 80

  appointments_php:
    build: ./easyappointments/docker/php-fpm
    working_dir: /var/www/html
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - './easyappointments:/var/www/html'
      - './easyappointments/docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'
    depends_on:
      - appointments_mysql

  appointments_nginx:
    image: 'nginx:1.23.3-alpine'
    working_dir: /var/www/html
    ports:
    - "8082:80"
    volumes:
      - './easyappointments:/var/www/html'
      - './easyappointments/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - appointments_php

  appointments_mysql:
    image: 'mysql:8.0'
    restart: unless-stopped
    volumes:
      - '${APP_DATA_DIR}/appointments/mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=easyappointments
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  appointments_phpmyadmin:
    image: 'phpmyadmin:5.2.1'
    environment:
      - 'PMA_HOST=appointments_mysql'
      - 'UPLOAD_LIMIT=102400K'
    depends_on:
      - appointments_mysql

  appointments_mailpit:
    image: 'axllent/mailpit:v1.7'
    volumes:
      - '${APP_DATA_DIR}/appointments/mailpit:/data'

  appointments_swagger:
    platform: linux/amd64
    image: swaggerapi/swagger-ui:v5.10.5
    volumes:
      - ./easyappointments/openapi.yml:/usr/share/nginx/html/openapi.yml
    environment:
      API_URL: openapi.yml
  
  appointments_baikal:
    image: ckulka/baikal:0.10.1-apache
    volumes:
      - ${APP_DATA_DIR}/appointments/baikal:/var/www/html
      - ${APP_DATA_DIR}/appointments/baikal/config:/var/www/baikal/config
      - ${APP_DATA_DIR}/appointments/baikal/data:/var/www/baikal/Specific
  
  appointments_openldap:
    image: osixia/openldap:1.5.0
    hostname: openldap
    volumes:
      - ${APP_DATA_DIR}/appointments/openldap/certificates:/container/service/slapd/assets/certs
      - ${APP_DATA_DIR}/appointments/openldap/slapd/database:/var/lib/ldap
      - ${APP_DATA_DIR}/appointments/openldap/slapd/config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=example
      - LDAP_DOMAIN=example.org
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_CONFIG_PASSWORD=config_pass
      - "LDAP_BASE_DN=dc=example,dc=org"
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=user
      - LDAP_READONLY_USER_PASSWORD=password

  appointments_phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    hostname: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=appointments_openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - appointments_openldap