version: "3.7"

services:
  app_proxy:
    environment:
      BASE_URL: "https://plebemr.com"
      APP_HOST: mgitreposerver-mgit-repo-server_web_1
      APP_PORT: 3003
      
  web:
    image: imyjimmy/mgit-repo-server:latest
    restart: on-failure
    stop_grace_period: 1m
    environment:
      REPOS_PATH: /private_repos
      NODE_ENV: production
      # PORT: 3003
    volumes:
      # Repository storage (contains both git repos and SQLite database)
      - ${APP_DATA_DIR}/repos:/private_repos
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s