# Base docker-compose configuration
# This file defines the core services shared across environments

services:
  admin-frontend:
    build: ./admin
    container_name: ${CONTAINER_PREFIX}_admin_frontend_1
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}

  patient-frontend:
    build: ./patient
    container_name: ${CONTAINER_PREFIX}_patient_frontend_1
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}

  mgit-web:
    image: imyjimmy/mgit-repo-server:latest
    container_name: ${CONTAINER_PREFIX}_web_1
    environment:
      - NODE_ENV=${NODE_ENV}
      - MGITPATH=/usr/local/bin
      - JWT_SECRET=${JWT_SECRET}
      - APPOINTMENTS_DB_HOST=${CONTAINER_PREFIX}_plebdoc_mysql_1
    restart: unless-stopped
    depends_on:
      - mysql

  gateway:
    image: imyjimmy/mgit-gateway:latest
    container_name: ${CONTAINER_PREFIX}_gateway_1
    environment:
      - CONTAINER_PREFIX=${CONTAINER_PREFIX}
    # volumes:
      # - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      - mgit-web

  mysql:
    image: mysql:8.0
    container_name: ${CONTAINER_PREFIX}_plebdoc_mysql_1
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=easyappointments
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
      - ../plebdoc-scheduler-service/init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: ${CONTAINER_PREFIX}_plebdoc_phpmyadmin_1
    environment:
      - PMA_HOST=${CONTAINER_PREFIX}_plebdoc_mysql_1
      - UPLOAD_LIMIT=102400K
      - PMA_USER=user
      - PMA_PASSWORD=password
    depends_on:
      - mysql
    restart: unless-stopped

  plebdoc-api:
    build: ../plebdoc-scheduler-service/api
    container_name: ${CONTAINER_PREFIX}_plebdoc_api_1
    environment:
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - NWC_CONNECTION_STRING=${NWC_CONNECTION_STRING}
      - ADMIN_NOSTR_PRIVATE_KEY=${ADMIN_NOSTR_PRIVATE_KEY}
      - DB_HOST=${CONTAINER_PREFIX}_plebdoc_mysql_1
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=easyappointments
      # Google OAuth
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - GOOGLE_REDIRECT_URI_ADMIN=${GOOGLE_REDIRECT_URI_ADMIN}
    depends_on:
      - mysql
    restart: unless-stopped

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: ${CONTAINER_PREFIX}_plebdoc_swagger_1
    environment:
      - SWAGGER_JSON_URL=http://localhost:3005/api-docs.json
      - API_URL=http://localhost:3005/api-docs.json
    depends_on:
      - plebdoc-api
    restart: unless-stopped

volumes:
  mysql_data:
  repos_data: